### ISSUE TITLE
Error after installation of v2.2.X

### ISSUE THREAD

**Issue by SanderBorgmans** [diffpy/pyobjcryst#30]
Hi,

I have tried to install the newest version of libobjcryst/pyobjcryst to be able to adapt the RadiationType attribute. The installation runs smoothly, but when trying to import pyobjcryst in python I get the followin error:

```
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyobjcryst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/.local/lib/python3.6/site-packages/pyobjcryst/__init__.py", line 51, in <module>
    from pyobjcryst.general import ObjCrystException
  File "/home/sander/.local/lib/python3.6/site-packages/pyobjcryst/general.py", line 23, in <module>
    from pyobjcryst._pyobjcryst import RadiationType
ImportError: /home/sander/.local/lib/python3.6/site-packages/pyobjcryst/_pyobjcryst.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN8ObjCryst20CreateCrystalFromCIFERNS_3CIFEbbbb

```
I get an identical error for the 2.2.0 as well as the 2.2.1 version. Could you help me fix this?

Thanks in advance!

All the best,
Sander

**Comment by vincefn** [comment]
It is hard to answer without knowing how you installed pyobjcryst. It seems you have installed in `.local`, which is really not recommended as this can be messy, and I suspect there may be an issue with library paths.

Can you try this rather in a conda environment ?

**Comment by SanderBorgmans** [comment]
Hi @vincefn,

Thanks for the quick response. I've installed both by pulling the code from github, and using the scons -j4 install
command. So for both I should have the latest version on the respective master branches (v2021.1.2 for libobjcryst and v2.2.1 for pyobjcryst). 

However, I redid the installation and noticed the pyobjcryst was being installed using python2 instead of python3 (my default python version for scons was python2 for some reason), which caused all kinds of issues between already existing versions of both pyobjcryst and libobjcryst. 

My apologies! I will close this issue now.

**Comment by SanderBorgmans** [comment]
Hi @vincefn,

Importing pyobjcryst is now no longer but it crashes when trying to calculate the XRD from a cif file. I'm getting the following error: 

`pyobjcryst.ObjCrystException: ScatteringData::CalcSinThetaLambda()       Cannot compute sin(theta)/lambda : there are no reflections !`

I used the following basic example code (I've included my cif file):

`import os
import pyobjcryst
import numpy as np
import matplotlib.pyplot as plt
from pyobjcryst.crystal import *
from pyobjcryst.scatteringpower import ScatteringPowerAtom
from pyobjcryst.atom import Atom
from pyobjcryst.polyhedron import MakeTetrahedron
from pyobjcryst.powderpattern import *
from pyobjcryst.radiation import RadiationType
from pyobjcryst.indexing import *
from pyobjcryst.molecule import *
from pyobjcryst.globaloptim import MonteCarlo
from pyobjcryst.io import xml_cryst_file_save_global


px = PowderPattern()
px.SetWavelength("Cu")

c = CreateCrystalFromCIF('0.cif')

diffData = px.AddPowderPatternDiffraction(c)

px.plot(hkl=True)
`
Might there be something wrong with the cif file?

Thanks in advance!
[cif_file.zip](https://github.com/diffpy/pyobjcryst/files/8089208/cif_file.zip)

**Comment by vincefn** [comment]
That's because you do not have any point in your powder pattern. Try with:
``` python
px = PowderPattern() 
px.SetWavelength("Cu")                                                                                                                                                                                                        

tth=np.deg2rad(np.arange(1,20,0.005))
px.SetPowderPatternX(tth)
px.SetPowderPatternObs(np.ones_like(tth))

c = CreateCrystalFromCIF('0.cif')

diffData = px.AddPowderPatternDiffraction(c)

px.plot()
```

**Comment by SanderBorgmans** [comment]
Worked like a charm! In a previous version I did not have to specify the X range (and had to execute px.Prepare()) when trying to calculate the PXRD. Thank you for the assistance!
