### ISSUE TITLE
pyobjcryst.radiation

### ISSUE THREAD

**Issue by FuccoVando** [diffpy/pyobjcryst#31]
Hi
I've some porblem importing some modules of pyobjcryst.
I've installed the packages on wsl ubuntu  but some mudules are missing. Due to this I'm not able to follow the guieded examples.
Below there's the output obtained by trying to import different modules.
As u can see by making python show up possible modules some of them miss (radiation, indexing, globalopt ....)
Do I miss some step/something?

For the installation I've followed the instructions on git

Python 3.7.13 (default, Mar 29 2022, 02:18:16)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyobjcryst
>>> import pyobjcryst.
pyobjcryst.ObjCrystException(            pyobjcryst.refinableobj
pyobjcryst.atom                          pyobjcryst.reflectionprofile
pyobjcryst.crystal                       pyobjcryst.scatterer
pyobjcryst.diffractiondatasinglecrystal  pyobjcryst.scatteringdata
pyobjcryst.general                       pyobjcryst.scatteringpower
pyobjcryst.io                            pyobjcryst.scatteringpowersphere
pyobjcryst.loadCrystal(                  pyobjcryst.spacegroup
pyobjcryst.molecule                      pyobjcryst.unitcell
pyobjcryst.polyhedron                    pyobjcryst.version
pyobjcryst.powderpattern                 pyobjcryst.zscatterer
pyobjcryst.pyobjcryst
>>> import pyobjcryst.radiation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyobjcryst.radiation'

Another issue is the following
Running this cell in jupiter notebook I've obtained the following message 

c = create_crystal_from_cif("http://scripts.iucr.org/cgi-bin/sendcif?dt3034sup1",
                            oneScatteringPowerPerElement=True,
                            connectAtoms=True)
print(c.GetFormula())
c.widget_3d()

Error loading preloads:
Could not find renderer

I've installe py3dmol and ipywidgets as written in the guide.
Any idea?

Thanks

**Comment by vincefn** [comment]
Hi Marco (I assume that's you),

Could you state _exactly_ which installation instructions you followed ? There are two shown on github, either using conda (the conda-forge or diffpy channels, see https://anaconda.org/search?q=pyobjcryst), or from source using scons. Normally all should work.

Best wishes,
Vincent (on vacation/travelling, response time may be slow)

**Comment by vincefn** [comment]
Also, regarding the 'renderer' error , there are a number of such reports if you google for it. Can you try reinstalling/upgrading jupyter ? Is this inside a browser or through an IDE (e.g. VSCode ?)

**Comment by FuccoVando** [comment]
Dear Vincent,
I've tested both forge and diffpy but only with diffpy i'am able to import pyobjcryst (having in any case the problem I've told you about with the other modules.)
Never tried with scons.
I link here two colab notebooks so that you can see what piece of code I use to install the package (in case you have time to do so).

I copied some piece of code from Simon's diffpy colab tutorial to download conda and install diffpy.

**diffpy installation**
https://colab.research.google.com/drive/1XYPX1yHlZpoLRm82e3EwUGdqJKWLboFe?usp=sharing

**forge installation**
https://colab.research.google.com/drive/1raW17_OtIWGbC_fxketPWlPttBJunJvg?usp=sharing

Thanks for the kind and quick answer!
Hope this will help you.
In next days I'll try the other commands which are present at https://anaconda.org/search?q=pyobjcryst

Best
Marco

**Comment by vincefn** [comment]
Dear Marco, I can't open the colab links you sent - you need to give the permission to open with the link.

You can have a look at the colab notebooks I used for testing -using the source install-:
* https://colab.research.google.com/drive/1avmZLHsP3uT326w8qlmLSo6TfBtj0bEP?usp=sharing
* https://colab.research.google.com/drive/1qVnqteKAp2GRMEYS8g4VX61DVCvOPzik?usp=sharing

(I just had to change a little those notebooks so they take my github sources rather than diffpy's, but it's just a picky consistency version test which fails otherwise).

On my mac the conda install works fine, but I'll have to see why your tests fail..

**Comment by vincefn** [comment]
(it seems only the first notebook I shared about manages to install pyobjcryst... not sure why....)

**Comment by FuccoVando** [comment]
Here there are the updated open-link

**diffpy**
https://colab.research.google.com/drive/1XYPX1yHlZpoLRm82e3EwUGdqJKWLboFe?usp=sharing
**forge**
https://colab.research.google.com/drive/1raW17_OtIWGbC_fxketPWlPttBJunJvg?usp=sharing

**Comment by vincefn** [comment]
From what I see the libobjcryst version installed (as a dependency to diffpy-cmi) is too old, from 2017.

Try a direct conda install of pyobjcryst and libobjcryst and make sure the versions installed are the last ones from the repositories.

**Comment by FuccoVando** [comment]
Thanks for the code. I'll look at it. 

Ok, I'll try. The repositories here on github are the last one pubblished. right?
Thanks

**Comment by FuccoVando** [comment]
I confirm that you're notebbok works fine.
By reproducing the same code to install packages into WSL ubuntu to work offline with VScode I still obtain errors during the installation of the packages cloned from git. (says that miss libbost python but build-essential and libboost-all-dev were installed)...
What is interesting is that using conda, conda-forge or any other repo pyobjcryst version retrieved is always 2.1.0 or previous, the same is true for libobjcryst which is 2017 version as you mentioned. This happen even if I specify the version of the package i want.
For the moment thanks a lot. I'll work on these errors.

**Comment by FuccoVando** [comment]
Off course Any other observation or advice is welcomed.

**Comment by FuccoVando** [comment]
Hi
At the end I managed to install the package 2.1.1 within conda but I had to do it manually with scons after cloning pyobjcrshyt, downloading libobjcryst.tar and solving some problems concerning libbost_python.
Now all modules can be imported without any problem but still I get an error message from plotting functions. 
```
/usr/local/lib/python3.7/dist-packages/pyobjcryst/powderpattern.py:125: RuntimeWarning: invalid value encountered in arcsin
  mtth = np.rad2deg(np.arcsin(m)) * 2
```
The same error I noticed is present also in your colab cimetidine structure solutions but in your case following steps are able to plot hkl indexes, in mine not. 
Seems that the problem comes from px.plot function when you call it for the second time  
```
p.plot(diff=False,fig=None,hkl=True)
```

Another error arises from the assignement of hkl indexes. Space group is found without any problems but once I try to print the plot with hkl i get this error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_439/3072774533.py in <module>
      4 
      5 # Plot with indexing in new figure
----> 6 p.plot(diff=False,fig=None,hkl=True)

~/anaconda3/envs/CrystApp/lib/python3.7/site-packages/pyobjcryst-2.2.1-py3.7-linux-x86_64.egg/pyobjcryst/powderpattern.py in plot(self, diff, hkl, figsize, fontsize_hkl, reset, **kwargs)
    143 
    144         if plot_hkl:
--> 145             self._do_plot_hkl(nb_max=100, fontsize_hkl=fontsize_hkl)
    146 
    147         # print PowderPatternDiffraction names

~/anaconda3/envs/CrystApp/lib/python3.7/site-packages/pyobjcryst-2.2.1-py3.7-linux-x86_64.egg/pyobjcryst/powderpattern.py in _do_plot_hkl(self, nb_max, fontsize_hkl)
    192         x = np.rad2deg(self.GetPowderPatternX())
    193         # Clear previous text (assumes only hkl were printed)
--> 194         plt.gca().texts = []
    195         iphase = 0
    196         for ic in range(self.GetNbPowderPatternComponent()):

AttributeError: can't set attribute
```
Indeed if I use 
```
p.plot(diff=False,fig=None,hkl=False)
```
No errors are generated

Otherwise following message appear.

Any idea?
Best

**Comment by vincefn** [comment]
The conda install issue may come from a dependency issue with diffpy-cmi if it is still installed.

Regarding the plot issue, this may be due to using colab which has limited interactive graphics, so some queries may fail and are not properly handled. On a notebook environment with better graphics (I python notebook or widgets allowed) it should work better.

Are you per chance coming to the ECM in August? I'll be there

**Comment by FuccoVando** [comment]
Errors were generated inside VSCode. I'll look at them.
Unfortunatelly no, But I'll be at ESRF in september i think.
Thanks

**Comment by vincefn** [comment]
Hi @FuccoVando, I've looked at the plotting issues, which are now fixed in the master branch. 

The error when plotting is due to matplotlib>=3.5 which does not allow changing the axes' texts attribute.

If you install matplotlib==3.4.3 it will work without re-installing pyobjcryst

**Comment by FuccoVando** [comment]
Problem solved!
Thank you so much for the great help.
Best
