### ISSUE TITLE
After using RemoveScatterer, the catalogue of athoms doesn't update

### ISSUE THREAD

**Issue by ji-ze** [diffpy/pyobjcryst#41]
Hello,
I generate a primitive lattice with random carbon atoms. If I remove an atom by RemoveScatterer(), the function GetFormula writes the original formula before removing an atom. If I use GetNbScatterer, I get a correct answer. It isn't practical, because I want to generate an electron density map, but I get the same result (before/after). I'm including my code. 
Thanks for answers.

```
from pyobjcryst.crystal import *

# some lines

c = Crystal(5, 5, 5, pi/2, pi/2, pi/2, "P1")

# some lines

i = nbAtoms
at = list()
carbon = ScatteringPowerAtom("C", "C")
c.AddScatteringPower(carbon)
while i > 0:
    # position = [random(), random(), random()]
    at.append(Atom(random(), random(), random(), f"C{i}", carbon, 1.0))
    c.AddScatterer(at[nbAtoms-i])
    import numpy as np

    darr = np.array(c.GetMinDistanceTable(0.0))
    minimum = darr.min()
    print(minimum)
    if minimum < min_distance:
        c.RemoveScatterer(at[nbAtoms-i])
        del(at[nbAtoms-i])
        i += 1
    i -= 1

formula = c.GetFormula()
print("Molecular formula:", formula)

c.RemoveScatterer(at[0])

formula = c.GetFormula()
print("Molecular formula:", formula)

```

![image](https://github.com/user-attachments/assets/79c37802-566f-4797-b6ef-a22237d69bf9)
(Output after removing 2 atoms. The 1st line is GetNbScatterer and 2nd is GetFormula)

**Comment by vincefn** [comment]
Thanks for the report.

For some reason, the `ScatteringComponentList` is not updated after removing the `Scatterer`, which leads to the non-updated formula.

As a temporary workaround, you can add a very small value to any scatterer coordinate, and it will force the update of the  `ScatteringComponentList`.

For example, add a single line:
    `c.GetScatterer(0).X += 0.0001`

**Comment by ji-ze** [comment]
Thank you for getting back to me.
It doesn't work. It works to add athom but it isn't practical.

**Comment by sbillinge** [comment]
@sbillinge reopening.  I don't think this is fixed, just a workaround reported.

**Comment by vincefn** [comment]
Yes, it's still on the todo list, but this needs to be done & tested first upstream in https://github.com/vincefn/objcryst, and then propagated to `libobjcryst`...

I need first to merge two `objcryst` branches, and only then I can have a look at this. Hopefully next week before EPDIC.

**Comment by sbillinge** [comment]
@vincefn looking forward to seeing you at EPDIC....

**Comment by vincefn** [comment]
This should be fixed in `libobjcryst 2024.2` - hopefully it'll be available in conda-forge tomorrow

**Comment by sbillinge** [comment]
@ji-ze please let us know if 2024-2 fixes this problem for you and we can close this issue.

**Comment by vincefn** [comment]
@ji-ze `libobjcryst=2024.2.1` finally went through on conda-forge, but the `pyobjcryst` conda package now needs to be updated. Probably two more days unless you install from source.

**Comment by vincefn** [comment]
I spoke too quickly - the libobjcryst built packages are missing the headers... I'll mark those as broken, sorry...

**Comment by vincefn** [comment]
build _1 of `libobjcryst` `2024.2.1` should be OK now - build 0 should soon be [marked as broken](https://github.com/conda-forge/admin-requests/pull/1080).

**Comment by vincefn** [comment]
pyobjcryst 2024.2 is out on conda, so this should be working without needing to compile from source.  Re-open if you still have issues.
