### ISSUE TITLE
SetIobs

### ISSUE THREAD

**Issue by ji-ze** [diffpy/pyobjcryst#42]
Is SetIobs (DiffractionDataSingleCrystal) available in the Python package?

**Comment by vincefn** [comment]
[Not yet](https://github.com/diffpy/pyobjcryst/blob/main/src/extensions/diffractiondatasinglecrystal_ext.cpp#L86C1-L87C1)

It is not yet implemented - for now you have to import from a file (`ImportHklIobs`, `ImportHklIobsSigma`..). There is also `SetIobsToIcalc`.

Would be easy to add though.

**Comment by vincefn** [comment]
pyobjcryst 2024.2 is out, which should give you the access to SetIobs and other new functions for DiffractionDataSingleCrystal
